apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-helm-app
  namespace: argocd
spec:
  project: homework-project # Связываем приложение с созданным выше проектом
  source:
    repoURL: https://maksimsolapai-gif.github.io/sa-36-26-jenkins/
 # Тот самый Helm-репозиторий из шага 2
    chart: jenkins # Название чарта в репозитории
    targetRevision: 0.1.0 # Версия чарта
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc # Локальный кластер
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
